package club.freechess.FreeChessClub;

import static org.junit.Assert.*;
import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Base64;
import org.junit.Test;

public class FicsTimesealTest {
    @Test
    public void acknowledgementMatchesExistingJavaScriptEncoding() {
        // Golden bytes generated by Session.encode("\u00029") with a fixed clock.
        assertEquals("xbC8taKlsNShmHmkgAo=", Base64.getEncoder().encodeToString(FicsTimeseal.acknowledgement(0)));
        assertEquals("xbC9saKts7yomJGkgAo=", Base64.getEncoder().encodeToString(FicsTimeseal.acknowledgement(1789764192180L)));
    }

    @Test
    public void savedPasswordEncodingMatchesJavaScriptForNonAsciiCharacters() {
        // Golden bytes from the actual Session.encode method with a fixed clock.
        assertEquals("zG2/dqLMtaSps3mW2LrCeHGnYH9hcXxwgAo=",
            Base64.getEncoder().encodeToString(FicsTimeseal.command("pässΩ", 1789764192180L)));
    }

    @Test
    public void probesAreAnsweredOnceAcrossEveryPossibleFrameSplit() throws Exception {
        byte[] input = "before[G]\0middle[G]\0after".getBytes(StandardCharsets.UTF_8);
        for (int split = 0; split <= input.length; split++) {
            FicsTimeseal seal = new FicsTimeseal();
            int[] replies = {0};
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            output.write(seal.receive(Arrays.copyOfRange(input, 0, split), () -> replies[0]++));
            output.write(seal.receive(Arrays.copyOfRange(input, split, input.length), () -> replies[0]++));
            assertEquals("beforemiddleafter", output.toString("UTF-8"));
            assertEquals(2, replies[0]);
        }
    }

    @Test
    public void ordinaryBracketsAndBinaryBytesAreNotLost() throws Exception {
        FicsTimeseal seal = new FicsTimeseal();
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        byte[] input = "[Game 1] [[G]\0\u00e9[Gx]".getBytes(StandardCharsets.UTF_8);
        int[] replies = {0};
        for (byte value : input) output.write(seal.receive(new byte[]{value}, () -> replies[0]++));
        assertEquals("[Game 1] [\u00e9[Gx]", output.toString("UTF-8"));
        assertEquals(1, replies[0]);
    }
}
